---
- name: Install Lab Tools and Stealthy Services
  hosts: all
  become: true
  vars:
    havoc_dir: "/opt/.syslogd"
    session_name: "systemd-logger"
    fake_service_name: "cloudsyncd"
    fake_service_exec: "/usr/bin/cloudsyncd"

  tasks:
    - name: Install base packages
      apt:
        name:
          - git
          - golang
          - make
          - screen
        state: present
        update_cache: yes

    - name: Clone Havoc to stealth directory
      git:
        repo: "https://github.com/HavocFramework/Havoc.git"
        dest: "{{ havoc_dir }}"
        version: "main"
        force: yes

    - name: Run install script
      shell: "./install.sh"
      args:
        chdir: "{{ havoc_dir }}"

    - name: Start Havoc in detached screen session
      shell: "screen -dmS {{ session_name }} ./teamserver"
      args:
        chdir: "{{ havoc_dir }}"

    - name: Create fake binary to simulate a legit process
      copy:
        dest: "{{ fake_service_exec }}"
        content: |
          #!/bin/bash
          while true; do sleep 300; done
        mode: "0755"

    - name: Create fake systemd service
      copy:
        dest: "/etc/systemd/system/{{ fake_service_name }}.service"
        content: |
          [Unit]
          Description=Azure Cloud Sync Daemon
          After=network.target

          [Service]
          Type=simple
          ExecStart={{ fake_service_exec }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start fake systemd service
      systemd:
        name: "{{ fake_service_name }}"
        enabled: true
        state: started
